### ISSUE TITLE
Asset pipeline vs Octopress Ink

### ISSUE THREAD

**Issue by mdotasia** [octopress/asset-pipeline#12]
This is ore a question than an issue.

the first thing which is not clear to me is what is the difference between the asset pipeline and Octopress Ink's asset capabilities. There seems to be some overlap, but the asset pipeline seems to have more configuration options. It's not clear whether I am supposed to use the assets pipeline with Octopress Ink or whether that's redundant.

**Comment by imathis** [comment]
Octopress Ink is for developers who are designing something to be reused by anyone. The idea is that I can design a theme or plugin and a user can easily install it and use it. I suspect that most people will not author Octopress Ink projects, though I did design it to be very easy to do. Users may use a collection of plugins but also have their own Javascripts or Stylesheets that they want to integrate. By adding the asset pipeline plugin, they can have their *local assets* slurped up into Octopress Ink's asset pipeline and loaded after plugins assets. This way, they don't have to do anything to modify their theme's layouts to include their site specific assets. Does this make sense?

**Comment by mdotasia** [comment]
Makes perfect sense!

What I actually wanna do is this: in my Ink plugin, I would like to manage certain dependencies like jQuery with bower and then let Ink pick selected files from the bower_components folder and have them slurped up into the generated CSS and JS files.

Can I do everything documented under *Configuration* in the Readme of the asset pipeline plugin (like customizing folders etc.) directly in an Ink plugin?

**Comment by imathis** [comment]
You cannot set the stylesheets or javascripts directory for Octopress Ink plugins. If you want to do something where a user can create a configuration to change the scripts or stylesheets that are built, you'll need to do something custom that isn't currently supported by Octopress Ink.

**Comment by imathis** [comment]
Octopress Ink plugins are really meant to ship assets which can conveniently integrate with a user's site. Users can disable individual files through the plugin's configuration and they will not be built into the combined assets. I hope you're able to figure out what you're attempting, but I think I've answered your question, so I'll close this issue.
