### ISSUE TITLE
"jekyll serve" with "watch" support?

### ISSUE THREAD

**Issue by jlgoolsbee** [octopress/asset-pipeline#14]
I may very well be missing something, but should I expect re-compilation and combination of scss/css files on-edit? When running `jekyll serve`, I see the standard "Regenerating: 1 file(s)" message when I save an scss file, but the resulting compiled/combined css file produced by `octopress-asset-pipeline` remains unchanged unless I kill the jekyll server and start it again.

**Comment by imathis** [comment]
Gosh, I'm sorry about this. I'll get a release out that fixes it soon.

**Comment by jlgoolsbee** [comment]
No worries – minor annoyance for now. Thanks!

**Comment by imathis** [comment]
Alright. I just released a new version of Octopress Ink which fixes this. Please test it out and let me know. if it works for you. Thanks for posting this issue!

**Comment by jlgoolsbee** [comment]
Yep – now, while running `jekyll serve`, edits made to local scss and css files are re-compiled/combined on the fly. Thanks!

An additional consideration / question: should (or can) the file produced on-the-fly change the hash in the generated filename (as it would on a standard `build` if there had been a change)? Right now it doesn't, and I can see a scenario where a user makes some edits while running `jekyll serve`, is happy with the result, and then goes to deploy their site without a re-build. Depending on their deployment strategy and their server's caching rules they might a.) not actually deploy the change, or b.) it might take a long time (until the cache expires) for the changes to be visible.

**Comment by imathis** [comment]
I wasn't sure which way to go on this one. It's a simple change to make the fingerprint flush with each build. I think it probably makes sense to do that. I think the only use case to avoid it is that you want to keep watching that file to see how it is being generated. Probably a low use-case scenario. I'll release another build with fingerprint flushing turned on.

**Comment by imathis** [comment]
I just released another gem build. Thanks for the feedback!
