### ISSUE TITLE
Path support

### ISSUE THREAD

**Issue by kogakure** [octopress/asset-pipeline#15]
It would be really useful to have tags `{% css_asset_path %}` and `{% js_asset_path %}`, which work in the same way as the tags, but don’t create a tag.

This way it would be possible to use the combined plugins path and do things like loading the styles asynchronous with something like [loadCSS](https://github.com/filamentgroup/loadCSS) to optimize mobile speed:

```html
<script>
  {% include loadCSS.js %}
  loadCSS("{% css_asset_path %}");
</script>
```

which would outout:

```html
<script>
  function loadCSS(e,n,o,t){"use strict";var d=window.document.createElement("link"),i=n||window.document.getElementsByTagName("script")[0],s=window.document.styleSheets;return d.rel="stylesheet",d.href=e,d.media="only x",t&&(d.onload=t),i.parentNode.insertBefore(d,i),d.onloadcssdefined=function(n){for(var o,t=0;t<s.length;t++)s[t].href&&s[t].href.indexOf(e)>-1&&(o=!0);o?n():setTimeout(function(){d.onloadcssdefined(n)})},d.onloadcssdefined(function(){d.media=o||"all"}),d}
  loadCSS("/stylesheets/all-c58e1f8c8c09a94b8f78d3718fcaf069.css");
</script>
```

**Comment by imathis** [comment]
Unfortunately, for this tag, your example would only work when all assets are combined. If a user configures the paths not to be combined, during debugging or something, the `{% css_asset_tag %}` will output each individual link tag and your script wouldn't work. I would have to create a way that you could loop through asset paths.

However, I don't really think this is that useful. Reading up on it, the purpose of loading CSS asynchronously is not for loading *all styles* this way, but for loading large CSS files after the core styles for your site have been loaded. If users get to the point where they've have optimized everything else except for loading CSS asynchronously, I'd be shocked. In most cases they could add gzipping to their server, use a CDN or recompress a single jpeg and get back any performance that this approach would have given them. CSS just isn't that big.

I suppose your CSS could be big if it contains embedded fonts or images, but in that case, don't add it to the asset pipeline. Load it separately using loadCSS.

I'm going to pass on this for now, but thank you for bringing it to my attention. If there is enough interest, or if I see this approach being adopted en masse, I'll reconsider.

**Comment by kogakure** [comment]
I would be fine with having the plugins css combined but as a path and not a tag because I load everything async to optimize the [critical render path](http://www.filamentgroup.com/lab/performance-rwd.html), which is an issue for mobile speed. Google would like to see sites to be optimized like [this](https://developers.google.com/speed/pagespeed/insights/?url=stefanimhoff.de) (compared to [this](https://developers.google.com/speed/pagespeed/insights/?url=octopress.org)). :smirk: Using plugins with Ink would force me to load them synchronously :pensive:

But I understand it’s still not a thing for the masses to optimize a page on this level. Thank you for your long explanation :thumbsup:

**Comment by imathis** [comment]
I'm still considering it. What affordances does this have for css media types?

**Comment by imathis** [comment]
Sorry, I see that now in the docs. I'll work on a pull request for making this very simple.

**Comment by imathis** [comment]
Alright, I've added this to Octopress Ink (which this asset-pipeline uses to do its work). Check out the PR and let me know what you think.
