### ISSUE TITLE
Compass support

### ISSUE THREAD

**Issue by drallgood** [octopress/asset-pipeline#8]
So far, I haven't been able to get this running in conjunction with compass (i.e. when using the jekyll-compass plugin).

Is there a way to get this to work? Did I miss something?

**Comment by imathis** [comment]
I haven't done any testing with Compass yet. When I developed this plugin Compass was not yet at 1.0 so I was waiting for the development to settle down. I'll take a look at see what it would take to work with Compass. If you want to help with that effort, I'd love it if you could post the source to an example site with what you're trying to do so I can see what it would take to get it to work.

**Comment by imathis** [comment]
This isn't going to happen. Compass is now unsupported and [Eyeglass](https://github.com/sass-eyeglass/eyeglass) is being built to take over some of its functionality. I don't plan to develop anything further with Compass.
