### ISSUE TITLE
Works great for css files but not js

### ISSUE THREAD

**Issue by chauncey-garrett** [octopress/asset-pipeline#9]
How can I troubleshoot this?

No js files are combined. All css/sass files are. Here's what I have in _config.yml:

```yml
asset_pipeline:
  combine_css: true
  combine_js: true
  compress_css: true
  compress_js: true
  order_js:
    - jquery-2.1.3.min.js
    - bigfoot.min.js
    - wufoo.js
  uglifier:
    - wufoo.js
```

**Comment by imathis** [comment]
Where are your javascript files located?

**Comment by chauncey-garrett** [comment]
{{ root_url }}/js

**Comment by imathis** [comment]
I'm not sure why this is happening, but your use of `uglifier` is incorrect. It should be a hash for configuring Uglifier. See the docs here: https://github.com/lautis/uglifier#usage

**Comment by imathis** [comment]
Does removing your faulty `uglifier` config change anything?

**Comment by chauncey-garrett** [comment]
Actually, I just realized my css files were at /css. Moving them to /_css will break the site's stylesheet even though the /public/stylesheets/all*.css is still produced.

**Comment by chauncey-garrett** [comment]
Let me try.

**Comment by chauncey-garrett** [comment]
Removing `uglifier` doesn't seem to help.

**Comment by chauncey-garrett** [comment]
On the css part, I probably need to update the references; that's likely the issue there.

**Comment by chauncey-garrett** [comment]
If you still have got the WIP site I sent you a couple of days ago that could help us.

**Comment by imathis** [comment]
Just so you know, this works by looking at Jekyll's static_files and picking out javascripts and stylesheets, adding them to the asset pipeline and removing them from Jekyll's control. If it's in a hidden directory it won't be picked up. That is except for sass or coffee script. Those get handled differently.

**Comment by chauncey-garrett** [comment]
Ok, so we don't want the files in _css or _js.

**Comment by chauncey-garrett** [comment]
I originally had them in /css and /js. The css stylesheet is being made but the js is not.

**Comment by imathis** [comment]
I still have access to the site archive you sent me. What should I do to reproduce this?

**Comment by chauncey-garrett** [comment]
Also to confirm, I do have the liquid tags in the site's head.

**Comment by chauncey-garrett** [comment]
Actually, I'll send you a new link so we can be certain we're on the same page.

Should just be a `jekyll build`.

**Comment by chauncey-garrett** [comment]
sent

**Comment by chauncey-garrett** [comment]
I did notice that there are not multiple js files in your test suite. That might be worth adding.

**Comment by chauncey-garrett** [comment]
Also, to confirm, this should fix the `uglifier` portion (using the built-in defaults; I mistook the {} for a [], an array!):

```yml
  uglifier: {
    :output => {
      :ascii_only => true,        # Escape non-ASCII characters
      :comments => :copyright,    # Preserve comments (:all, :jsdoc, :copyright, :none, Regexp (see below))
      :inline_script => false,    # Escape occurrences of </script in strings
      :quote_keys => false,       # Quote keys in object literals
      :max_line_len => 32 * 1024, # Maximum line length in minified code
      :bracketize => false,       # Bracketize if, for, do, while or with statements, even if their body is a single statement
      :semicolons => true,        # Separate statements with semicolons
      :preserve_line => false,    # Preserve line numbers in outputs
      :beautify => false,         # Beautify output
      :indent_level => 4,         # Indent level in spaces
      :indent_start => 0,         # Starting indent level
      :space_colon => false,      # Insert space before colons (only with beautifier)
      :width => 80,               # Specify line width when beautifier is used (only with beautifier)
      :preamble => nil            # Preamble for the generated JS file. Can be used to insert any code or comment.
    },
    :mangle => {
      :eval => false,             # Mangle names when eval of when is used in scope
      :except => ["$super"],      # Argument names to be excluded from mangling
      :sort => false,             # Assign shorter names to most frequently used variables. Often results in bigger output after gzip.
      :toplevel => false          # Mangle names declared in the toplevel scope
    },                            # Mangle variable and function names, set to false to skip mangling
    :compress => {
      :sequences => true,         # Allow statements to be joined by commas
      :properties => true,        # Rewrite property access using the dot notation
      :dead_code => true,         # Remove unreachable code
      :drop_debugger => true,     # Remove debugger; statements
      :unsafe => false,           # Apply "unsafe" transformations
      :conditionals => true,      # Optimize for if-s and conditional expressions
      :comparisons => true,       # Apply binary node optimizations for comparisons
      :evaluate => true,          # Attempt to evaluate constant expressions
      :booleans => true,          # Various optimizations to boolean contexts
      :loops => true,             # Optimize loops when condition can be statically determined
      :unused => true,            # Drop unreferenced functions and variables
      :hoist_funs => true,        # Hoist function declarations
      :hoist_vars => false,       # Hoist var declarations
      :if_return => true,         # Optimizations for if/return and if/continue
      :join_vars => true,         # Join consecutive var statements
      :cascade => true,           # Cascade sequences
      :negate_iife => true,       # Negate immediately invoked function expressions to avoid extra parens
      :pure_getters => false,     # Assume that object property access does not have any side-effects
      :pure_funcs => nil,         # List of functions without side-effects. Can safely discard function calls when the result value is not used
      :drop_console => false,     # Drop calls to console.* functions
      :angular => false           # Process @ngInject annotations
      :keep_fargs => false        # Preserve unused function arguments
    },                            # Apply transformations to code, set to false to skip
    :define => {},                # Define values for symbol replacement
    :enclose => false,            # Enclose in output function wrapper, define replacements as key-value pairs
    :source_filename => nil,      # The filename of the input file
    :source_root => nil,          # The URL of the directory which contains :source_filename
    :output_filename => nil,      # The filename or URL where the minified output can be found
    :input_source_map => nil,     # The contents of the source map describing the input
    :screw_ie8 => false,          # Don't bother to generate safe code for IE8
    :source_map_url => false,     # Url for source mapping to be appended in minified source
    :source_url => false          # Url to original source to be appended in minified source
  }
```

**Comment by imathis** [comment]
You need to add the gem to your `gems:` config. :)

```
gems:
    - octopress-asset-pipeline
```

**Comment by chauncey-garrett** [comment]
lol, one of those!

**Comment by imathis** [comment]
Alternatively if you organize your plugins under a bundler group, you don't need to define them twice. For example, your site might have:

```
group :jekyll_plugins do
    gem 'octopress-ink'
    gem 'octopress-linkblog'
    gem 'octopress-asset-pipeline'
    gem 'octopress-date-format'
    gem 'octopress-solarized'
    gem 'octopress-include-tag'
    gem 'octopress-escape-code'
    gem 'octopress-filters'
    gem 'octopress-render-tag'
    gem 'octopress-codefence'
    gem 'octopress-quote-tag'
    gem 'octopress-video-tag'
    gem 'jekyll-redirect-from'
    gem 'jemoji'
    gem 'jekyll-archives'
    gem 'uglifier'
    gem 'octopress-feeds'
    gem 'jekyll-sitemap'
end
```

**Comment by imathis** [comment]
Also I should say you have a CSS parse error on line 161 of your woof-theme.css:

```
{* Custom Fonts Break Dropdown Selection in IE *;
```

That is not a legit css comment :)

**Comment by imathis** [comment]
Once you fix that error you'll have some JS parsing errors. If you're going to include minified versions of your JS, you probably don't want to uglify them, double compression doesn't usually turn out well.

**Comment by chauncey-garrett** [comment]
Now that one's on WuFoo.

**Comment by chauncey-garrett** [comment]
Is the uglifier selective? It looks to me like it applies to **all** js files.

**Comment by imathis** [comment]
Poor. WuFoo, never learned that preprocessors are good even if only helping you not write busted CSS.

**Comment by imathis** [comment]
@chauncey-garrett At this point, uglifier is not. Mainly because I'd have to compress each file separately and then combine them which would make it take longer to build and it may cause issues with code interoperability given that each code snippet will be isolated in its own closure (I think).

I'm thinking it may be worth trying though. I will say, you never want to add compressed css to a project if you have an asset pipeline. Those compressed distributions are for people who just include them manually.

**Comment by chauncey-garrett** [comment]
Hmm, good to know. (I'm learning all this off the cuff).

So in my case, would you recommend using the pre-compressed JS (since it's likely already been checked for compression issues) or the uncompressed JS (since I would end up with one file)?

**Comment by imathis** [comment]
I'd recommend using non-compressed JS libraries and letting it be combined into one JS file. Additional HTTP requests are often the biggest problem with slowing down your site.

**Comment by chauncey-garrett** [comment]
> Additional HTTP requests are often the biggest problem with slowing down your site.

That's what I've been reading about, so good to know!

**Comment by imathis** [comment]
I've been thinking about it and because it's such a common practice for people to include already compressed JS in their projects, I'll probably avoid compressing anything with the name .min.js in the title. Then I'll add those to the beginning of the build, compressing the rest before concatenating it.

I can't think of a reason that would break things.

**Comment by imathis** [comment]
I just released version 1.1.7 which should allow you to add minified javascripts and it won't try to compress them again. Also it will add them to the front of the build by default, treating them like libraries. If you want to give it a try, let me know how it works for you.

**Comment by chauncey-garrett** [comment]
I think that is a wise choice: doing so provides the benefits of compression while eliminating issues arising from it.

I tried v1.1.7. It appears to load the JS with minified files first. So that works! However, I'm having an odd issue where the stylesheets are borked after a successful build. This happens even when I have _config.yml set like so:

```yml
asset_pipeline:
  combine_css: false
  combine_js: true
  compress_css: false
  compress_js: false
```

If I comment out `    - octopress-asset-pipeline` from `gems`, there is no problem.

**Comment by imathis** [comment]
Can you describe what borked means in this case? Would I be able to test this with the site you shared with me earlier?

**Comment by chauncey-garrett** [comment]
I should've been more descriptive. Sorry. I'll email over some images and yes it's the same site I've been working on.

**Comment by imathis** [comment]
I don't know what the deal is with the copy of your site that I have here, but it's not working for me. Would you mind sending me another?

**Comment by chauncey-garrett** [comment]
Sent!

--
**Chauncey**

**Comment by imathis** [comment]
If found the culprit. Your `projects/dropshare-theme/` there are a bunch of CSS files which are getting included in the build. The asset pipeline plugin takes all css that Jekyll finds and adds stylesheet link tags for them.

This may be a situation where I need to change how this plugin operates. Right now I'm grabbing all the static files and snagging assets from them. If people are planning to use css files for individual pages, I may need to change this behavior and have a "blessed" directory where css and js assets are read from.

I'll have to think about it.

Also I noticed that your `_includes/head` manually includes the `appbox.css` and `main.css`. With the `{% css_asset_tag %}` adding these individually is unnecessary.

**Comment by chauncey-garrett** [comment]
> If found the culprit. Your projects/dropshare-theme/ there are a bunch of CSS files which are getting included in the build. The asset pipeline plugin takes all css that Jekyll finds and adds stylesheet link tags for them.

That makes sense then! Perhaps this is bad practice, but the entire projects folder is basically a clone of several Github repos I wanted to showcase. The idea was to only have to update the files once (basically adding YAML front-matter and making a few formatting changes) instead of on both the Github repo and the site. Then a `git merge` from the master branch would bring in future updates.

> This may be a situation where I need to change how this plugin operates. Right now I'm grabbing all the static files and snagging assets from them. If people are planning to use css files for individual pages, I may need to change this behavior and have a "blessed" directory where css and js assets are read from.

> I'll have to think about it.

I like the idea of being able to throw everything into one folder and be done with it. It's straightforward and simple.

Just brainstorming... Alternatively, could have an "excludes" directory. This may add more flexibility for those who need it (for whatever reason).

> Also I noticed that your _includes/head manually includes the appbox.css and main.css. With the {% css_asset_tag %} adding these individually is unnecessary.

Didn't want to remove them till I was sure I wanted to include the asset-pipeline. Don't think it would change things but should've commented them out anyhow.

**Comment by imathis** [comment]
Alright. I just released version 2.0. It only reads from configured directories for javascripts and stylesheets. You can configure them, but by default it looks in `css` or  `stylesheets` and `js` or `javascripts`. Other files in your site source are left alone.

**Comment by chauncey-garrett** [comment]
Checking it out now... BTW, saw your post on Octopress. Congrats! Let me know how I can help and I'll see what I can do. It's been very insightful working with you over the past week so thanks!

**Comment by imathis** [comment]
@chauncey-garrett Just keep messing around and asking for help. Your willingness to try this stuff out has helped me make some significant improvements and find several bugs. Thanks!

**Comment by chauncey-garrett** [comment]
Glad to know I've been a help and not a bother! :) 

Ok, here's a thought for ya:

I've seen some scripts that are recommended to be placed in `head` while others are *required* to be placed in the `footer`. When using the Octopress asset pipeline, using the single `{% js_asset_tag %}` only allows you to call the JS scripts in one location or the other. Is this going to turn into a headache down the road?

**Comment by chauncey-garrett** [comment]
Alright, I think I found a bug.

I have both compressed and uncompressed JS files. Since we made a change to push the compressed JS files to the top, it appears that that automatically overrides whatever setting is assigned under `_config.yml`. *i.e.*, if I have the files 

- 1.js
- 2.min.js

and `_config.yml` is set like so:

```yml
asset_pipeline:
  combine_js: true
  order_js:
    - 1.js
    - 2.min.js
```

they will be ordered in the combined file in the unexpected order:

```
2.min.js
1.js
```

In my case, this means that `jquery.min.js` is loaded after `bigfoot.min.js`, breaking the nifty footnotes.

Was there a particular reason to push the minified JS files to the top? Perhaps so that you can compress the others and concatenate them in as you go?

**Comment by imathis** [comment]
As I think about this some more, you're right. I need to find a way to support order and minified javascripts. That will require compiling each javascript file independently and probably doing some caching. Thanks for helping me through the runaround.
